#!/bin/sh


cp -r ./assets ipkbuild/data/mnt/games/froggo
cp -r ./audios ipkbuild/data/mnt/games/froggo
cp ./FroggosAdventure.py ipkbuild/data/mnt/games/froggo/FroggosAdventure.py
cp ./icon.png ipkbuild/data/mnt/games/froggo/icon.png
cp ./readme.txt ipkbuild/data/mnt/games/froggo/readme.txt

cd ./ipkbuild

cd ./control
tar --owner=0 --group=0 -czvf ../control.tar.gz ./*
cd ..

cd ./data
tar --owner=0 --group=0 -czvf ../data.tar.gz ./*
cd ..


ar r froggosadventure.ipk ./data.tar.gz ./control.tar.gz ./debian-binary

